{
 "title": "ManagedKube - Kubernetes Cost Attribution",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Grand Total" },
  {
   "title": "Total  Cost 30 Days",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "format": "currencyUSD",
   "valueName": "max",
   "targets": [
    {
     "expr": "(sum(mk_pod_cost{duration=\"minute\"}) * 60 * 24 * 30) + \n(sum(mk_node_cost{duration=\"minute\"}) * 60 * 24 * 30) + \n(sum(mk_persisten_volume_cost{duration=\"minute\"}) * 60 * 24 * 30)"
    }
   ]
  },
  {
   "title": "Total  Cost 24 Hours",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "format": "currencyUSD",
   "valueName": "max",
   "targets": [
    {
     "expr": "(sum(mk_pod_cost{duration=\"minute\"}) * 60 * 24) + \n(sum(mk_node_cost{duration=\"minute\"}) * 60 * 24) + \n(sum(mk_persisten_volume_cost{duration=\"minute\"}) * 60 * 24)"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "content": "# Compute Cost" },
  {
   "title": "Total Compute Cost 30 Days",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "format": "currencyUSD",
   "valueName": "max",
   "targets": [
    { "expr": "sum(mk_pod_cost) * 60 * 24 *30" }
   ]
  },
  {
   "title": "Total Compute Cost 24 Hours",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "format": "currencyUSD",
   "valueName": "max",
   "targets": [
    { "expr": "sum(mk_pod_cost) * 60 * 24" }
   ]
  },
  {
   "title": "Compute Cost Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mk_pod_cost{duration=\"minute\"}) by (namespace_name) * 60 * 24"
    }
   ]
  },
  {
   "title": "Compute Cost Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mk_pod_cost{duration=\"minute\"}) by (namespace_name) * 60"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "content": "# Instance Cost" },
  {
   "title": "Node List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(mk_node_cost{duration=\"minute\"}) by (node_name, instance_type, cost_per_hour)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mk_node_cost{duration=\"minute\"}) by (node_name)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Total Node Cost",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(mk_node_cost) * 60 * 24" }
   ]
  },
  {
   "title": "Total Node Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mk_node_cost) * 60 * 24 * 30"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 }, "content": "# Persistent Volume Cost" },
  {
   "title": "Persistent Volumes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mk_persisten_volume_cost{duration=\"minute\"}) by (namespace_name)",
     "legendFormat": "{{ namespace_name }}"
    }
   ]
  },
  {
   "title": "Total Persistent Volume Cost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mk_persisten_volume_cost) * 60 * 24"
    }
   ]
  },
  {
   "title": "Total Persistent Volume Cost",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mk_persisten_volume_cost) * 60 * 24 * 30"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
   "content": "# Contact Us\nFeel free to contact us with any questions or comments.  We would love to hear from you.\n\nsupport@managedkube.com\n"
  }
 ]
}